<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Projects</title>

<!--radix_placeholder_navigation_in_header-->
<meta name="distill:offset" content=""/>

<script type="application/javascript">

  window.headroom_prevent_pin = false;

  window.document.addEventListener("DOMContentLoaded", function (event) {

    // initialize headroom for banner
    var header = $('header').get(0);
    var headerHeight = header.offsetHeight;
    var headroom = new Headroom(header, {
      tolerance: 5,
      onPin : function() {
        if (window.headroom_prevent_pin) {
          window.headroom_prevent_pin = false;
          headroom.unpin();
        }
      }
    });
    headroom.init();
    if(window.location.hash)
      headroom.unpin();
    $(header).addClass('headroom--transition');

    // offset scroll location for banner on hash change
    // (see: https://github.com/WickyNilliams/headroom.js/issues/38)
    window.addEventListener("hashchange", function(event) {
      window.scrollTo(0, window.pageYOffset - (headerHeight + 25));
    });

    // responsive menu
    $('.distill-site-header').each(function(i, val) {
      var topnav = $(this);
      var toggle = topnav.find('.nav-toggle');
      toggle.on('click', function() {
        topnav.toggleClass('responsive');
      });
    });

    // nav dropdowns
    $('.nav-dropbtn').click(function(e) {
      $(this).next('.nav-dropdown-content').toggleClass('nav-dropdown-active');
      $(this).parent().siblings('.nav-dropdown')
         .children('.nav-dropdown-content').removeClass('nav-dropdown-active');
    });
    $("body").click(function(e){
      $('.nav-dropdown-content').removeClass('nav-dropdown-active');
    });
    $(".nav-dropdown").click(function(e){
      e.stopPropagation();
    });
  });
</script>

<style type="text/css">

/* Theme (user-documented overrideables for nav appearance) */

.distill-site-nav {
  color: rgba(255, 255, 255, 0.8);
  background-color: #0F2E3D;
  font-size: 15px;
  font-weight: 300;
}

.distill-site-nav a {
  color: inherit;
  text-decoration: none;
}

.distill-site-nav a:hover {
  color: white;
}

@media print {
  .distill-site-nav {
    display: none;
  }
}

.distill-site-header {

}

.distill-site-footer {

}


/* Site Header */

.distill-site-header {
  width: 100%;
  box-sizing: border-box;
  z-index: 3;
}

.distill-site-header .nav-left {
  display: inline-block;
  margin-left: 8px;
}

@media screen and (max-width: 768px) {
  .distill-site-header .nav-left {
    margin-left: 0;
  }
}


.distill-site-header .nav-right {
  float: right;
  margin-right: 8px;
}

.distill-site-header a,
.distill-site-header .title {
  display: inline-block;
  text-align: center;
  padding: 14px 10px 14px 10px;
}

.distill-site-header .title {
  font-size: 18px;
  min-width: 150px;
}

.distill-site-header .logo {
  padding: 0;
}

.distill-site-header .logo img {
  display: none;
  max-height: 20px;
  width: auto;
  margin-bottom: -4px;
}

.distill-site-header .nav-image img {
  max-height: 18px;
  width: auto;
  display: inline-block;
  margin-bottom: -3px;
}



@media screen and (min-width: 1000px) {
  .distill-site-header .logo img {
    display: inline-block;
  }
  .distill-site-header .nav-left {
    margin-left: 20px;
  }
  .distill-site-header .nav-right {
    margin-right: 20px;
  }
  .distill-site-header .title {
    padding-left: 12px;
  }
}


.distill-site-header .nav-toggle {
  display: none;
}

.nav-dropdown {
  display: inline-block;
  position: relative;
}

.nav-dropdown .nav-dropbtn {
  border: none;
  outline: none;
  color: rgba(255, 255, 255, 0.8);
  padding: 16px 10px;
  background-color: transparent;
  font-family: inherit;
  font-size: inherit;
  font-weight: inherit;
  margin: 0;
  margin-top: 1px;
  z-index: 2;
}

.nav-dropdown-content {
  display: none;
  position: absolute;
  background-color: white;
  min-width: 200px;
  border: 1px solid rgba(0,0,0,0.15);
  border-radius: 4px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.1);
  z-index: 1;
  margin-top: 2px;
  white-space: nowrap;
  padding-top: 4px;
  padding-bottom: 4px;
}

.nav-dropdown-content hr {
  margin-top: 4px;
  margin-bottom: 4px;
  border: none;
  border-bottom: 1px solid rgba(0, 0, 0, 0.1);
}

.nav-dropdown-active {
  display: block;
}

.nav-dropdown-content a, .nav-dropdown-content .nav-dropdown-header {
  color: black;
  padding: 6px 24px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.nav-dropdown-content .nav-dropdown-header {
  display: block;
  padding: 5px 24px;
  padding-bottom: 0;
  text-transform: uppercase;
  font-size: 14px;
  color: #999999;
  white-space: nowrap;
}

.nav-dropdown:hover .nav-dropbtn {
  color: white;
}

.nav-dropdown-content a:hover {
  background-color: #ddd;
  color: black;
}

.nav-right .nav-dropdown-content {
  margin-left: -45%;
  right: 0;
}

@media screen and (max-width: 768px) {
  .distill-site-header a, .distill-site-header .nav-dropdown  {display: none;}
  .distill-site-header a.nav-toggle {
    float: right;
    display: block;
  }
  .distill-site-header .title {
    margin-left: 0;
  }
  .distill-site-header .nav-right {
    margin-right: 0;
  }
  .distill-site-header {
    overflow: hidden;
  }
  .nav-right .nav-dropdown-content {
    margin-left: 0;
  }
}


@media screen and (max-width: 768px) {
  .distill-site-header.responsive {position: relative; min-height: 500px; }
  .distill-site-header.responsive a.nav-toggle {
    position: absolute;
    right: 0;
    top: 0;
  }
  .distill-site-header.responsive a,
  .distill-site-header.responsive .nav-dropdown {
    display: block;
    text-align: left;
  }
  .distill-site-header.responsive .nav-left,
  .distill-site-header.responsive .nav-right {
    width: 100%;
  }
  .distill-site-header.responsive .nav-dropdown {float: none;}
  .distill-site-header.responsive .nav-dropdown-content {position: relative;}
  .distill-site-header.responsive .nav-dropdown .nav-dropbtn {
    display: block;
    width: 100%;
    text-align: left;
  }
}

/* Site Footer */

.distill-site-footer {
  width: 100%;
  overflow: hidden;
  box-sizing: border-box;
  z-index: 3;
  margin-top: 30px;
  padding-top: 30px;
  padding-bottom: 30px;
  text-align: center;
}

/* Headroom */

d-title {
  padding-top: 6rem;
}

@media print {
  d-title {
    padding-top: 4rem;
  }
}

.headroom {
  z-index: 1000;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
}

.headroom--transition {
  transition: all .4s ease-in-out;
}

.headroom--unpinned {
  top: -100px;
}

.headroom--pinned {
  top: 0;
}

/* adjust viewport for navbar height */
/* helps vertically center bootstrap (non-distill) content */
.min-vh-100 {
  min-height: calc(100vh - 100px) !important;
}

</style>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet"/>
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet"/>
<script src="site_libs/headroom-0.9.4/headroom.min.js"></script>
<script src="site_libs/autocomplete-0.37.1/autocomplete.min.js"></script>
<script src="site_libs/fuse-6.4.1/fuse.min.js"></script>

<script type="application/javascript">

function getMeta(metaName) {
  var metas = document.getElementsByTagName('meta');
  for (let i = 0; i < metas.length; i++) {
    if (metas[i].getAttribute('name') === metaName) {
      return metas[i].getAttribute('content');
    }
  }
  return '';
}

function offsetURL(url) {
  var offset = getMeta('distill:offset');
  return offset ? offset + '/' + url : url;
}

function createFuseIndex() {

  // create fuse index
  var options = {
    keys: [
      { name: 'title', weight: 20 },
      { name: 'categories', weight: 15 },
      { name: 'description', weight: 10 },
      { name: 'contents', weight: 5 },
    ],
    ignoreLocation: true,
    threshold: 0
  };
  var fuse = new window.Fuse([], options);

  // fetch the main search.json
  return fetch(offsetURL('search.json'))
    .then(function(response) {
      if (response.status == 200) {
        return response.json().then(function(json) {
          // index main articles
          json.articles.forEach(function(article) {
            fuse.add(article);
          });
          // download collections and index their articles
          return Promise.all(json.collections.map(function(collection) {
            return fetch(offsetURL(collection)).then(function(response) {
              if (response.status === 200) {
                return response.json().then(function(articles) {
                  articles.forEach(function(article) {
                    fuse.add(article);
                  });
                })
              } else {
                return Promise.reject(
                  new Error('Unexpected status from search index request: ' +
                            response.status)
                );
              }
            });
          })).then(function() {
            return fuse;
          });
        });

      } else {
        return Promise.reject(
          new Error('Unexpected status from search index request: ' +
                      response.status)
        );
      }
    });
}

window.document.addEventListener("DOMContentLoaded", function (event) {

  // get search element (bail if we don't have one)
  var searchEl = window.document.getElementById('distill-search');
  if (!searchEl)
    return;

  createFuseIndex()
    .then(function(fuse) {

      // make search box visible
      searchEl.classList.remove('hidden');

      // initialize autocomplete
      var options = {
        autoselect: true,
        hint: false,
        minLength: 2,
      };
      window.autocomplete(searchEl, options, [{
        source: function(query, callback) {
          const searchOptions = {
            isCaseSensitive: false,
            shouldSort: true,
            minMatchCharLength: 2,
            limit: 10,
          };
          var results = fuse.search(query, searchOptions);
          callback(results
            .map(function(result) { return result.item; })
          );
        },
        templates: {
          suggestion: function(suggestion) {
            var img = suggestion.preview && Object.keys(suggestion.preview).length > 0
              ? `<img src="${offsetURL(suggestion.preview)}"</img>`
              : '';
            var html = `
              <div class="search-item">
                <h3>${suggestion.title}</h3>
                <div class="search-item-description">
                  ${suggestion.description || ''}
                </div>
                <div class="search-item-preview">
                  ${img}
                </div>
              </div>
            `;
            return html;
          }
        }
      }]).on('autocomplete:selected', function(event, suggestion) {
        window.location.href = offsetURL(suggestion.path);
      });
      // remove inline display style on autocompleter (we want to
      // manage responsive display via css)
      $('.algolia-autocomplete').css("display", "");
    })
    .catch(function(error) {
      console.log(error);
    });

});

</script>

<style type="text/css">

.nav-search {
  font-size: x-small;
}

/* Algolioa Autocomplete */

.algolia-autocomplete {
  display: inline-block;
  margin-left: 10px;
  vertical-align: sub;
  background-color: white;
  color: black;
  padding: 6px;
  padding-top: 8px;
  padding-bottom: 0;
  border-radius: 6px;
  border: 1px #0F2E3D solid;
  width: 180px;
}


@media screen and (max-width: 768px) {
  .distill-site-nav .algolia-autocomplete {
    display: none;
    visibility: hidden;
  }
  .distill-site-nav.responsive .algolia-autocomplete {
    display: inline-block;
    visibility: visible;
  }
  .distill-site-nav.responsive .algolia-autocomplete .aa-dropdown-menu {
    margin-left: 0;
    width: 400px;
    max-height: 400px;
  }
}

.algolia-autocomplete .aa-input, .algolia-autocomplete .aa-hint {
  width: 90%;
  outline: none;
  border: none;
}

.algolia-autocomplete .aa-hint {
  color: #999;
}
.algolia-autocomplete .aa-dropdown-menu {
  width: 550px;
  max-height: 70vh;
  overflow-x: visible;
  overflow-y: scroll;
  padding: 5px;
  margin-top: 3px;
  margin-left: -150px;
  background-color: #fff;
  border-radius: 5px;
  border: 1px solid #999;
  border-top: none;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion {
  cursor: pointer;
  padding: 5px 4px;
  border-bottom: 1px solid #eee;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion:last-of-type {
  border-bottom: none;
  margin-bottom: 2px;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion .search-item {
  overflow: hidden;
  font-size: 0.8em;
  line-height: 1.4em;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion .search-item h3 {
  font-size: 1rem;
  margin-block-start: 0;
  margin-block-end: 5px;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion .search-item-description {
  display: inline-block;
  overflow: hidden;
  height: 2.8em;
  width: 80%;
  margin-right: 4%;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion .search-item-preview {
  display: inline-block;
  width: 15%;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion .search-item-preview img {
  height: 3em;
  width: auto;
  display: none;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion .search-item-preview img[src] {
  display: initial;
}

.algolia-autocomplete .aa-dropdown-menu .aa-suggestion.aa-cursor {
  background-color: #eee;
}
.algolia-autocomplete .aa-dropdown-menu .aa-suggestion em {
  font-weight: bold;
  font-style: normal;
}

</style>


<!--/radix_placeholder_navigation_in_header-->
<!--radix_placeholder_site_in_header-->
<!--/radix_placeholder_site_in_header-->

<style type="text/css">
body {
  padding-top: 60px;
}
</style>
<style type="text/css">
/* base variables */

/* Edit the CSS properties in this file to create a custom
   Distill theme. Only edit values in the right column
   for each row; values shown are the CSS defaults.
   To return any property to the default,
   you may set its value to: unset
   All rows must end with a semi-colon.                      */

/* Optional: embed custom fonts here with `@import`          */
/* This must remain at the top of this file.                 */



html {
  /*-- Main font sizes --*/
  --title-size:      50px;
  --body-size:       1.06rem;
  --code-size:       14px;
  --aside-size:      12px;
  --fig-cap-size:    13px;
  /*-- Main font colors --*/
  --title-color:     #000000;
  --header-color:    rgba(0, 0, 0, 0.8);
  --body-color:      rgba(0, 0, 0, 0.8);
  --aside-color:     rgba(0, 0, 0, 0.6);
  --fig-cap-color:   rgba(0, 0, 0, 0.6);
  /*-- Specify custom fonts ~~~ must be imported above   --*/
  --heading-font:    sans-serif;
  --mono-font:       monospace;
  --body-font:       sans-serif;
  --navbar-font:     sans-serif;  /* websites + blogs only */
}

/*-- ARTICLE METADATA --*/
d-byline {
  --heading-size:    0.6rem;
  --heading-color:   rgba(0, 0, 0, 0.5);
  --body-size:       0.8rem;
  --body-color:      rgba(0, 0, 0, 0.8);
}

/*-- ARTICLE TABLE OF CONTENTS --*/
.d-contents {
  --heading-size:    18px;
  --contents-size:   13px;
}

/*-- ARTICLE APPENDIX --*/
d-appendix {
  --heading-size:    15px;
  --heading-color:   rgba(0, 0, 0, 0.65);
  --text-size:       0.8em;
  --text-color:      rgba(0, 0, 0, 0.5);
}

/*-- WEBSITE HEADER + FOOTER --*/
/* These properties only apply to Distill sites and blogs  */

.distill-site-header {
  --title-size:       18px;
  --text-color:       rgba(255, 255, 255, 0.8);
  --text-size:        15px;
  --hover-color:      white;
  --bkgd-color:       #0F2E3D;
}

.distill-site-footer {
  --text-color:       rgba(255, 255, 255, 0.8);
  --text-size:        15px;
  --hover-color:      white;
  --bkgd-color:       #0F2E3D;
}

/*-- Additional custom styles --*/
/* Add any additional CSS rules below                      */
</style>
<style type="text/css">
/* base variables */

/* Edit the CSS properties in this file to create a custom
   Distill theme. Only edit values in the right column
   for each row; values shown are the CSS defaults.
   To return any property to the default,
   you may set its value to: unset
   All rows must end with a semi-colon.                      */

/* Optional: embed custom fonts here with `@import`          */
/* This must remain at the top of this file.                 */
/* Optional: embed custom fonts here with `@import`          */
/* This must remain at the top of this file.                 */
@import url('https://fonts.googleapis.com/css2?family=Amiri');
@import url('https://fonts.googleapis.com/css2?family=Bitter');
@import url('https://fonts.googleapis.com/css2?family=DM+Mono');
@import url('https://fonts.googleapis.com/css2?family=Roboto+Serif:wght@100&display=swap');

html {
  /*-- Main font sizes --*/
  --title-size:      50px;
  --body-size:       1.06rem;
  --code-size:       14px;
  --aside-size:      12px;
  --fig-cap-size:    13px;
  /*-- Main font colors --*/
  --title-color:     #000000;
  --header-color:    rgba(0, 0, 0, 0.8);
  --body-color:      rgba(0, 0, 0, 0.8);
  --aside-color:     rgba(0, 0, 0, 0.6);
  --fig-cap-color:   rgba(0, 0, 0, 0.6);
  /*-- Specify custom fonts ~~~ must be imported above   --*/
  --heading-font:    "Roboto Serif", sans-serif;
  --mono-font:       "DM Mono", monospace;
  --body-font:       "Bitter", sans-serif;
  --navbar-font:     "Roboto Serif", sans-serif;
}

/*-- ARTICLE METADATA --*/
d-byline {
  --heading-size:    0.6rem;
  --heading-color:   rgba(0, 0, 0, 0.5);
  --body-size:       0.8rem;
  --body-color:      rgba(0, 0, 0, 0.8);
}

/*-- ARTICLE TABLE OF CONTENTS --*/
.d-contents {
  --heading-size:    18px;
  --contents-size:   13px;
}

/*-- ARTICLE APPENDIX --*/
d-appendix {
  --heading-size:    15px;
  --heading-color:   rgba(0, 0, 0, 0.65);
  --text-size:       0.8em;
  --text-color:      rgba(0, 0, 0, 0.5);
}

/*-- WEBSITE HEADER + FOOTER --*/
/* These properties only apply to Distill sites and blogs  */

.distill-site-header {
  --title-size:       20px;    
  --text-color:       #ffffff; /* edited */
  --text-size:        15px;
  --hover-color:      #2403fc; /* edited */
  --bkgd-color:       #82c1e6; /* edited */
}

.distill-site-footer {
  --text-color:       rgba(255, 255, 255, 0.8);
  --text-size:        15px;
  --hover-color:      white;
  --bkgd-color:       #0F2E3D;
}

/*-- Additional custom styles --*/
/* Add any additional CSS rules below                      */

/* Change bullets */
ul > li::marker {
  font-size: 1.125em;
  color: #ff414b;
}

/* Change link appearance */
d-article a {
  border-bottom: 2px solid #ffd8db;
  text-decoration: none;
}</style>
<style type="text/css">
/* base style */

/* FONT FAMILIES */

:root {
  --heading-default: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif;
  --mono-default: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
  --body-default: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif;
}

body,
.posts-list .post-preview p,
.posts-list .description p {
  font-family: var(--body-font), var(--body-default);
}

h1, h2, h3, h4, h5, h6,
.posts-list .post-preview h2,
.posts-list .description h2 {
  font-family: var(--heading-font), var(--heading-default);
}

d-article div.sourceCode code,
d-article pre code {
  font-family: var(--mono-font), var(--mono-default);
}


/*-- TITLE --*/
d-title h1,
.posts-list > h1 {
  color: var(--title-color, black);
}

d-title h1 {
  font-size: var(--title-size, 50px);
}

/*-- HEADERS --*/
d-article h1,
d-article h2,
d-article h3,
d-article h4,
d-article h5,
d-article h6 {
  color: var(--header-color, rgba(0, 0, 0, 0.8));
}

/*-- BODY --*/
d-article > p,  /* only text inside of <p> tags */
d-article > ul, /* lists */
d-article > ol {
  color: var(--body-color, rgba(0, 0, 0, 0.8));
  font-size: var(--body-size, 1.06rem);
}


/*-- CODE --*/
d-article div.sourceCode code,
d-article pre code {
  font-size: var(--code-size, 14px);
}

/*-- ASIDE --*/
d-article aside {
  font-size: var(--aside-size, 12px);
  color: var(--aside-color, rgba(0, 0, 0, 0.6));
}

/*-- FIGURE CAPTIONS --*/
figure .caption,
figure figcaption,
.figure .caption {
  font-size: var(--fig-cap-size, 13px);
  color: var(--fig-cap-color, rgba(0, 0, 0, 0.6));
}

/*-- METADATA --*/
d-byline h3 {
  font-size: var(--heading-size, 0.6rem);
  color: var(--heading-color, rgba(0, 0, 0, 0.5));
}

d-byline {
  font-size: var(--body-size, 0.8rem);
  color: var(--body-color, rgba(0, 0, 0, 0.8));
}

d-byline a,
d-article d-byline a {
  color: var(--body-color, rgba(0, 0, 0, 0.8));
}

/*-- TABLE OF CONTENTS --*/
.d-contents nav h3 {
  font-size: var(--heading-size, 18px);
}

.d-contents nav a {
  font-size: var(--contents-size, 13px);
}

/*-- APPENDIX --*/
d-appendix h3 {
  font-size: var(--heading-size, 15px);
  color: var(--heading-color, rgba(0, 0, 0, 0.65));
}

d-appendix {
  font-size: var(--text-size, 0.8em);
  color: var(--text-color, rgba(0, 0, 0, 0.5));
}

d-appendix d-footnote-list a.footnote-backlink {
  color: var(--text-color, rgba(0, 0, 0, 0.5));
}

/*-- WEBSITE HEADER + FOOTER --*/
.distill-site-header .title {
  font-size: var(--title-size, 18px);
  font-family: var(--navbar-font), var(--heading-default);
}

.distill-site-header a,
.nav-dropdown .nav-dropbtn {
  font-family: var(--navbar-font), var(--heading-default);
}

.nav-dropdown .nav-dropbtn {
  color: var(--text-color, rgba(255, 255, 255, 0.8));
  font-size: var(--text-size, 15px);
}

.distill-site-header a:hover,
.nav-dropdown:hover .nav-dropbtn {
  color: var(--hover-color, white);
}

.distill-site-header {
  font-size: var(--text-size, 15px);
  color: var(--text-color, rgba(255, 255, 255, 0.8));
  background-color: var(--bkgd-color, #0F2E3D);
}

.distill-site-footer {
  font-size: var(--text-size, 15px);
  color: var(--text-color, rgba(255, 255, 255, 0.8));
  background-color: var(--bkgd-color, #0F2E3D);
}

.distill-site-footer a:hover {
  color: var(--hover-color, white);
}</style>
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/pandoc/header-attrs.js"></script>
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/jquerylib/lib/3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/bootstrap/js/bootstrap.min.js"></script>
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/bootstrap/shim/html5shiv.min.js"></script>
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/bootstrap/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/navigation-1.1/tabsets.js"></script>
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/navigation-1.1/codefolding.js"></script>
<link href="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/highlightjs/default.css" rel="stylesheet" />
<script src="/Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmd/h/highlightjs/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">



<!--radix_placeholder_navigation_before_body-->
<header class="header header--fixed" role="banner">
<nav class="distill-site-nav distill-site-header">
<div class="nav-left">
<a href="index.html" class="title">Katelyn Toigo</a>
<input id="distill-search" class="nav-search hidden" type="text" placeholder="Search..."/>
</div>
<div class="nav-right">
<a href="index.html">Home</a>
<a href="Resume.html">Resume</a>
<div class="nav-dropdown">
<button class="nav-dropbtn">
Projects
 
<span class="down-arrow">&#x25BE;</span>
</button>
<div class="nav-dropdown-content">
<a href="proj1.html">Project 1</a>
<a href="proj2.html">Project 2</a>
</div>
</div>
<a href="blog.html">Blog</a>
<a href="javascript:void(0);" class="nav-toggle">&#9776;</a>
</div>
</nav>
</header>
<!--/radix_placeholder_navigation_before_body-->
<!--radix_placeholder_site_before_body-->
<!--/radix_placeholder_site_before_body-->

<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Resume.html">Resume</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="proj1.html">Project 1</a>
    </li>
    <li>
      <a href="proj2.html">Project 2</a>
    </li>
  </ul>
</li>
<li>
  <a href="blog.html">Blog</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Projects</h1>

</div>


<div id="principal-components-analysis-to-analyze-food-nutrients" class="section level2">
<h2>1. Principal Components Analysis to Analyze Food Nutrients</h2>
<div id="overview" class="section level3">
<h3>Overview</h3>
<p>This script uses principal components analysis to analyze nutrient information for raw fruits and vegetables from the USDA National Nutrient Database (FoodDataCentral). Principal components analysis is an ordination method allowing us to understand as much about our multivariate data as possible in a simplified number of dimensions. Here, I’ll use the <code>nutrients</code> data from the USDA to explore variable relationships and clustering. I will only use the measurements that are in grams (protein, fat, carbohydrates, sugar, fiber), and I will only look at restaurant foods, baked products, and beef products.</p>
<p><strong>Data citation:</strong> United States Department of Agriculture. <a href="https://fdc.nal.usda.gov/index.html" class="uri">https://fdc.nal.usda.gov/index.html</a></p>
</div>
<div id="attach-required-packages" class="section level3">
<h3>Attach required packages:</h3>
<pre class="r"><code>knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
 
library(tidyverse)
library(here)
library(ggfortify) # For PCA biplot
library(patchwork)
library(broom)</code></pre>
</div>
<div id="read-in-the-data" class="section level3">
<h3>Read in the data</h3>
<pre class="r"><code>nutrients &lt;- read_csv(here(&quot;data&quot;, &quot;usda_nutrients.csv&quot;))</code></pre>
</div>
<div id="filter-the-data" class="section level3">
<h3>Filter the data</h3>
<pre class="r"><code># Filter food groups for restaurant foods, baked products, and beef products.
nutrients_filter &lt;- nutrients %&gt;% 
  filter(FoodGroup == c(&quot;Restaurant Foods&quot;, &quot;Baked Products&quot;, &quot;Beef Products&quot;))</code></pre>
</div>
<div id="run-the-pca" class="section level3">
<h3>Run the PCA</h3>
<pre class="r"><code>nutrients_pca &lt;- nutrients_filter %&gt;% 
  select(ends_with(&#39;_g&#39;)) %&gt;% 
  scale() %&gt;% # scale the selected variables and pass to the prcomp() function
  prcomp()</code></pre>
</div>
<div id="create-a-biplot-using-autoplot" class="section level3">
<h3>Create a biplot using autoplot</h3>
<pre class="r"><code>autoplot(nutrients_pca,
        data = nutrients_filter,
        loadings = TRUE,
        colour = &#39;FoodGroup&#39;, # colour needs to be British spelling
        loadings.label = TRUE,
        loadings.colour = &quot;black&quot;,
        loadings.label.colour = &quot;black&quot;,
        loadings.label.vjust = -0.5) +
  theme_classic()</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><strong>Figure 1.</strong> PCA biplot between PC1 and PC2 when looking at protein, fiber, carbohydrates, sugar, and fat of baked products, beef products, and restaurant foods.</p>
</div>
<div id="summary" class="section level3">
<h3>Summary</h3>
<ul>
<li>All three food groups seem to have distinct clusters.</li>
<li>Beef products associate more strongly with protein than with the other nutrients.</li>
<li>Fiber, carbs, and sugars tend to be more similar to each other than to protein. They are positively correlated.</li>
<li>Protein is about 180 degrees different than carbs and sugars. This means they have a correlation of -1.</li>
<li>Fiber and fat have a correlation of 0 since they are about 90 degrees.</li>
<li>Baked products are more similar to restaurant food than beef products based on these variables.</li>
<li>Of the three clusters, beef products and baked products are the most different.</li>
</ul>
</div>
</div>
<div id="analysis-of-seawater" class="section level2">
<h2>2. Analysis of Seawater</h2>
<div id="overview-1" class="section level3">
<h3>Overview</h3>
<p>This analysis will look at the relationship between oxygen saturation of seawater off California’s coast and several physical and chemical variables including oxygen saturation, water temperature, water salinity, water depth, phosphate concentration, and nitrite concentrations.</p>
<p>Data citation: CalCOFI data are available for use without restriction. Data downloaded from <a href="https://calcofi.org/ccdata.html" class="uri">https://calcofi.org/ccdata.html</a>. Accessed 1/10/2022.</p>
</div>
<div id="attach-required-packages-1" class="section level3">
<h3>Attach required packages</h3>
<pre class="r"><code># load packages
library(tidyverse)
library(here)
library(AICcmodavg)
library(equatiomatic)</code></pre>
</div>
<div id="read-in-the-data-1" class="section level3">
<h3>Read in the data</h3>
<pre class="r"><code>seawater_samples &lt;- read_csv(here(&#39;data&#39;, &#39;calcofi_seawater_samples.csv&#39;))</code></pre>
</div>
<div id="clean-the-data" class="section level3">
<h3>Clean the data</h3>
<pre class="r"><code>seawater_clean &lt;- seawater_samples %&gt;% 
  drop_na() %&gt;% 
  rename(temp = t_deg_c, # variables are renamed so they are easier to work with and understand
         depth = depth_m,
         phosphate = po4u_m,
         nitrite = no2u_m)</code></pre>
</div>
<div id="create-linear-regression-models-using-functions-to-store-the-equations" class="section level3">
<h3>Create linear regression models using functions to store the equations</h3>
<p>Model 1 is oxygen saturation as a function of water temperature, salinity, and phosphate concentration.</p>
<p>Model 2 is oxygen saturation as a function of water temperature, salinity, phosphate concentration, and depth.</p>
<p>A third model has also been added. Model 3 is oxygen saturation as a function of water temperature, salinity, phosphate concentration, nitrite concentration, and depth.</p>
<pre class="r"><code>f1 &lt;- o2sat ~ temp + salinity + phosphate
mdl1 &lt;- lm(f1, data = seawater_clean)

f2 &lt;- o2sat ~ temp + salinity + phosphate + depth
mdl2 &lt;- lm(f2, data = seawater_clean)

f3 &lt;- o2sat ~ temp + salinity + phosphate + + nitrite + depth
mdl3 &lt;- lm(f3, data = seawater_clean)</code></pre>
</div>
<div id="use-aic-to-compare-the-models" class="section level3">
<h3>Use AIC to compare the models</h3>
<p>AIC = Akaike Information Criterion</p>
<p>Model with the lowest AIC is the preferred model. Ideally, the best model is lower than the next best model by at least 2.0. A difference of 2 indicates a significant difference in model fit.</p>
<pre class="r"><code>AICc(mdl1) # AICc() corrects for sample size</code></pre>
<pre><code>## [1] 619.0251</code></pre>
<pre class="r"><code>AICc(mdl2)</code></pre>
<pre><code>## [1] 616.6048</code></pre>
<pre class="r"><code>AICc(mdl3)</code></pre>
<pre><code>## [1] 613.5962</code></pre>
<pre class="r"><code>AICcmodavg::aictab(list(mdl1, mdl2, mdl3))</code></pre>
<pre><code>## 
## Model selection based on AICc:
## 
##      K   AICc Delta_AICc AICcWt Cum.Wt      LL
## Mod3 7 613.60       0.00   0.78   0.78 -299.19
## Mod2 6 616.60       3.01   0.17   0.95 -301.85
## Mod1 5 619.03       5.43   0.05   1.00 -304.19</code></pre>
<ul>
<li><p>AIC of model 1 = 619.0251</p></li>
<li><p>AIC of model 2 = 616.6048</p></li>
<li><p>AIC of model 3 = 613.5962</p></li>
<li><p>The AIC of model 1 &gt; model 2 &gt; model 3.</p></li>
<li><p>Model 3 is lower than model 2 by 3.01 and lower than model 1 by 5.43, so since it is lower by at least 2, model 3 is the preferred model.</p></li>
<li><p>Model 3 is the preferred model via the AIC method.</p></li>
</ul>
</div>
<div id="use-10-fold-cross-validation-to-compare-the-models" class="section level3">
<h3>Use 10-fold cross validation to compare the models</h3>
<p>Root-mean-square error is the scoring method.</p>
<pre class="r"><code>folds &lt;- 10 # number of folds
fold_vec &lt;- rep(1:folds, length.out = nrow(seawater_clean)) # fold vector is repeating over each fold
table(fold_vec)</code></pre>
<pre><code>## fold_vec
##  1  2  3  4  5  6  7  8  9 10 
## 10 10 10 10 10 10 10 10 10 10</code></pre>
<pre class="r"><code>set.seed(42) # allows others to get same set of random numbers if they try to replicate this work

seawater_fold &lt;- seawater_clean %&gt;% 
  mutate(group = sample(fold_vec, size = n(), replace = FALSE))</code></pre>
<p>Create root-mean-square error function.</p>
<pre class="r"><code>calc_rmse &lt;- function(x, y) {
  rmse_result &lt;- (x-y)^2 %&gt;% mean() %&gt;% sqrt()
  return(rmse_result)
}</code></pre>
<p>Calculate over all folds and take the average.</p>
<pre class="r"><code>rmse_df &lt;- data.frame() # Create a blank data frame.

# Below is a for loop - loops through all 10 folds.
for(i in 1:folds) {
  kfold_test_df &lt;-seawater_fold %&gt;% 
    filter(group == i) # in group i
  kfold_train_df &lt;-seawater_fold %&gt;% 
    filter(group != i) # not in group i
  
  kfold_mdl1 &lt;- lm(f1, data = kfold_train_df)
  kfold_mdl2 &lt;- lm(f2, data = kfold_train_df)
  kfold_mdl3 &lt;- lm(f3, data = kfold_train_df)
  
  kfold_pred_df &lt;- kfold_test_df %&gt;% 
    mutate(mdl1 = predict(kfold_mdl1, kfold_test_df),
           mdl2 = predict(kfold_mdl2, .), # the period is a shortcut that says you are predicting on the data frame
           mdl3 = predict(kfold_mdl3, .)) 
  kfold_rmse &lt;- kfold_pred_df %&gt;% 
    summarize(rmse_mdl1 = calc_rmse(mdl1, o2sat),
              rmse_mdl2 = calc_rmse(mdl2, o2sat),
              rmse_mdl3 = calc_rmse(mdl3, o2sat))
  
  #Store the last chunk above by combining with the blank data frame from above.
  rmse_df &lt;- bind_rows(rmse_df, kfold_rmse)
}

rmse_df %&gt;% 
  summarize(mean_rmse_mdl1 = mean(rmse_mdl1),
            mean_rmse_mdl2 = mean(rmse_mdl2),
            mean_rmse_mdl3 = mean(rmse_mdl3))</code></pre>
<pre><code>##   mean_rmse_mdl1 mean_rmse_mdl2 mean_rmse_mdl3
## 1       4.976605       4.876322       4.795063</code></pre>
<ul>
<li><p>Model 1 RMSE = 4.976605</p></li>
<li><p>Model 2 RMSE = 4.876322</p></li>
<li><p>Model 3 RMSE = 4.795063</p></li>
<li><p>Model 3 has the lowest root-mean-square error meaning it has the lowest error when predicting data.</p></li>
<li><p>Model 3 is the preferred model via the k-fold cross validation method using RMSE scoring.</p></li>
</ul>
<p><strong>Both AIC and k-fold cross validation using root-mean-square error as the scoring method indicate model 3 to be the preferred model.</strong></p>
</div>
<div id="the-coefficients-for-the-final-predictive-model-are-identified" class="section level3">
<h3>The coefficients for the final predictive model are identified:</h3>
<pre class="r"><code>final_mdl &lt;- lm(f3, data = seawater_clean)
summary(final_mdl)</code></pre>
<pre><code>## 
## Call:
## lm(formula = f3, data = seawater_clean)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -25.3273  -2.3744   0.0158   2.3748  19.4893 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 149.93538   93.39120   1.605   0.1117    
## temp         -0.46764    0.41548  -1.126   0.2632    
## salinity     -0.78711    2.92993  -0.269   0.7888    
## phosphate   -37.37466    2.45287 -15.237   &lt;2e-16 ***
## nitrite      14.66437    6.46880   2.267   0.0257 *  
## depth        -0.01789    0.01591  -1.124   0.2637    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.972 on 94 degrees of freedom
## Multiple R-squared:  0.9597, Adjusted R-squared:  0.9575 
## F-statistic: 447.1 on 5 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div id="the-final-model" class="section level3">
<h3>The final model:</h3>
<p><span class="math display">\[
\begin{aligned}
\operatorname{o2sat} &amp;= \alpha + \beta_{1}(\operatorname{temp}) + \beta_{2}(\operatorname{salinity}) + \beta_{3}(\operatorname{phosphate})\ + \\
&amp;\quad \beta_{4}(\operatorname{nitrite}) + \beta_{5}(\operatorname{depth}) + \epsilon
\end{aligned}
\]</span></p>
<p>Where:</p>
<ul>
<li><p>o2sat = oxygen saturation</p></li>
<li><p>temp = water temperature in degrees Celsius</p></li>
<li><p>salinity = salinity of the water</p></li>
<li><p>phosphate = phosphate concentration in micro moles per liter</p></li>
<li><p>nitrite = nitrite concentration in micro moles per liter</p></li>
<li><p>depth = depth in meters</p></li>
</ul>
</div>
<div id="the-final-model-with-numbers" class="section level3">
<h3>The final model with numbers:</h3>
<p><span class="math display">\[
\begin{aligned}
\operatorname{\widehat{o2sat}} &amp;= 149.94 - 0.47(\operatorname{temp}) - 0.79(\operatorname{salinity}) - 37.37(\operatorname{phosphate})\ + \\
&amp;\quad 14.66(\operatorname{nitrite}) - 0.02(\operatorname{depth})
\end{aligned}
\]</span></p>
</div>
</div>
<div id="binary-logistic-regression-to-identify-palmetto-species" class="section level2">
<h2>3. Binary Logistic Regression to Identify Palmetto Species</h2>
<div id="overview-2" class="section level3">
<h3>Overview</h3>
<p>This script uses variables such as plant height, canopy length, canopy width, and the number of green leaves to classify whether palmettos are of species <em>Serenoa repens</em> or <em>Sabal etonia</em>. Binary logistic regression is used to test feasibility.</p>
<p>Data was collected from 1981 to 2017 in south-central Florida. It includes information regarding year, plant type, species, site, habitat, treatment, survival, height, canopy length, canopy width, number of green leaves, scape, new leaves, canopy, if long, comments, and biomass.</p>
<p><strong>Data citation:</strong> Abrahamson, W.G. 2019. Survival, growth and biomass estimates of two dominant palmetto species of south-central Florida from 1981 - 2017, ongoing at 5-year intervals ver 1. Environmental Data Initiative. <a href="https://doi.org/10.6073/pasta/f2f96ec76fbbd4b9db431c79a770c4d5" class="uri">https://doi.org/10.6073/pasta/f2f96ec76fbbd4b9db431c79a770c4d5</a></p>
<pre class="r"><code>library(tidyverse)
library(here)
library(GGally)
library(broom)
library(jtools)
library(caret)
library(AICcmodavg)
library(data.table)
library(knitr)</code></pre>
<pre class="r"><code>palmetto &lt;- read_csv(here(&quot;data&quot;, &quot;palmetto.csv&quot;)) # Read in the data</code></pre>
</div>
<div id="wrangle-the-data" class="section level3">
<h3>Wrangle the data</h3>
<p>Select columns for use in the analysis, change values in the species column to species names, and convert the species column to a factor class.</p>
<pre class="r"><code>palmetto_clean &lt;- palmetto %&gt;% # Clean the data table
  select(species, height:green_lvs) %&gt;% # Select only the columns I need for analysis, the colon means &quot;all the way over to&quot;
  drop_na()

# Change the values 1 and 2 in the species column to actual species names. 1 = Serenoa repens, 2 = Sabal etonia
palmetto_clean$species &lt;- ifelse(palmetto_clean$species==1,&#39;Serenoa repens&#39;,&#39;Sabal etonia&#39;) 

# Convert the  species column to a factor class
palmetto_clean$species &lt;- as.factor(palmetto_clean$species) 

# levels(palmetto_clean$species) in the console revealed Sabal etonia is factor level 0 and Serenoa repens is factor level 1</code></pre>
</div>
<div id="visualize-the-data-to-identify-trends." class="section level3">
<h3>Visualize the data to identify trends.</h3>
<p>Differences in height, canopy length, canopy width, and green leaves for <em>Serenoa repens</em> or <em>Sabal etonia</em>.</p>
<pre class="r"><code>ggplot(data = palmetto_clean, aes(x = height, y = length)) +
  geom_point(aes(color = species)) + 
  labs(title = &#39;Distribution of Height vs. Canopy Length of Two Palmetto Species&#39;, 
       x = &#39;Plant Height (cm)&#39;, 
       y = &#39;Canopy Length (cm)&#39;, 
       color = &quot;Species&quot;) + # title, axis labels, and legend title
  theme_minimal() # sets the theme of the graph - for visual purposes</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p><strong>Figure 1.</strong> The relationship between canopy length (cm) and maximum plant height (cm) is shown for each species. <em>Sabal etonia</em> is shown in red. <em>Serenoa repens</em> is shown in blue.</p>
<pre class="r"><code>ggplot(data = palmetto_clean, aes(x = width, y = green_lvs)) +
  geom_point(aes(color = species)) + 
  labs(title = &#39;Distribution of Canopy Width vs. Number of Green Leaves of Two Palmetto Species&#39;, 
x = &#39;Canopy Width (cm)&#39;, 
y = &#39;Number of Green Leaves&#39;, 
color = &quot;Species&quot;) + # title, axis labels, and legend title
  theme_minimal() # sets the theme of the graph - for visual purposes</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p><strong>Figure 2.</strong> The relationship between the number of green leaves and canopy width (cm) is shown for each species. <em>Sabal etonia</em> is shown in red. <em>Serenoa repens</em> is shown in blue.</p>
<p>Based on these plots, the number of green leaves is the most likely variable to help classify the species correctly. It shows the most difference between species. Canopy width, plant height, and canopy length showed similar trends between species.</p>
</div>
<div id="binary-logistic-regression" class="section level3">
<h3>Binary logistic regression</h3>
<pre class="r"><code># Store formulas
f1 &lt;- species ~ height + length + width + green_lvs

f2 &lt;- species ~ height + width + green_lvs</code></pre>
<pre class="r"><code># Binomial logistic regression for model 1 which includes height + length + width + green_lvs.
palm_blr1 &lt;- glm(formula = f1, 
                    data = palmetto_clean,
                    family = &#39;binomial&#39;)</code></pre>
<pre class="r"><code># Binomial logistic regression for model 2 which includes height + width + green_lvs and does not include length.
palm_blr2 &lt;- glm(formula = f2, 
                    data = palmetto_clean,
                    family = &#39;binomial&#39;)</code></pre>
</div>
<div id="identify-which-model-performs-better" class="section level3">
<h3>Identify which model performs better</h3>
<p>Compare the models using AICc</p>
<pre class="r"><code>AICcmodavg::aictab(list(palm_blr1, palm_blr2)) # this function compares competing models</code></pre>
<pre><code>## 
## Model selection based on AICc:
## 
##      K    AICc Delta_AICc AICcWt Cum.Wt       LL
## Mod1 5 5194.57       0.00      1      1 -2592.28
## Mod2 4 5987.48     792.91      0      1 -2989.74</code></pre>
<ul>
<li>Model 1 is better because the AIC for model 1 (5194.57) is more than two less than the AIC of model 2 (5987.48).</li>
</ul>
<p>Compare with a 10-fold cross-validation, using prediction accuracy as our metric.</p>
<pre class="r"><code># Using `caret` (&quot;**C**lassification **A**nd **RE**gression **T**raining&quot;):
set.seed(123) 

# tr_ctrl &lt;- trainControl(method = &quot;cv&quot;, number = 10)
tr_ctrl &lt;- trainControl(method = &quot;repeatedcv&quot;, number = 10, repeats = 10)

# Train the model
model1 &lt;- train(f1, data = palmetto_clean, 
               method = &quot;glm&quot;, family = &#39;binomial&#39;,
               trControl = tr_ctrl)

model2 &lt;- train(f2, data = palmetto_clean, 
               method = &quot;glm&quot;, family = &#39;binomial&#39;,
               trControl = tr_ctrl)</code></pre>
<ul>
<li><p>Model 1 (92% accurate) is more accurate than model 2 (90% accurate) according to 10-fold cross validation.</p></li>
<li><p><strong>Based on both AIC values and 10-fold cross validation, model 1 is the better model.</strong></p></li>
</ul>
</div>
<div id="train-model-1-using-the-entire-dataset-and-create-a-finalized-table-containing-the-binary-logistic-regression-model-results" class="section level3">
<h3>Train model 1 using the entire dataset, and create a finalized table containing the binary logistic regression model results</h3>
<pre class="r"><code>final_mdl &lt;- glm(formula = f1, 
                 data = palmetto_clean, 
                 family = &#39;binomial&#39;)</code></pre>
<p><strong>Table 1.</strong> Model 1 binary logistic regression model results.</p>
<pre class="r"><code>### Get a tidy version w/ broom:
final_mdl_tidy &lt;- broom::tidy(final_mdl)

setnames(final_mdl_tidy, old=c(&quot;term&quot;,&quot;estimate&quot;, &quot;std.error&quot;, &quot;statistic&quot;, &quot;p.value&quot;), new=c(&quot;Term&quot;,&quot;Estimate&quot;, &quot;Standard Error&quot;, &quot;z-value&quot;, &quot;p-value&quot;))

kable(final_mdl_tidy)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="right">Estimate</th>
<th align="right">Standard Error</th>
<th align="right">z-value</th>
<th align="right">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-3.2266851</td>
<td align="right">0.1420708</td>
<td align="right">-22.71180</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">0.0292173</td>
<td align="right">0.0023061</td>
<td align="right">12.66984</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">length</td>
<td align="right">-0.0458233</td>
<td align="right">0.0018661</td>
<td align="right">-24.55600</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">width</td>
<td align="right">-0.0394434</td>
<td align="right">0.0021000</td>
<td align="right">-18.78227</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">green_lvs</td>
<td align="right">1.9084747</td>
<td align="right">0.0388634</td>
<td align="right">49.10728</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<ul>
<li><p>The model is predicting the likelihood that the species is a <em>Serenoa repens</em> because the factor level of <em>Serenoa repens</em> is 1.</p></li>
<li><p>All variables are statistically significant.</p></li>
<li><p>Higher length and width would be less likely to be <em>Serenoa repens</em> because the value is negative.</p></li>
<li><p>Higher height and more green leaves would be more likely to be a <em>Serenoa repens</em> because the value is positive. This makes sense when looking at graphs above.</p></li>
</ul>
</div>
<div id="evaluation-of-how-successfully-this-model-would-classify-a-plant-as-the-correct-species-using-a-50-cutoff." class="section level3">
<h3>Evaluation of how successfully this model would “classify” a plant as the correct species, using a 50% cutoff.</h3>
<p><strong>Table 2.</strong> Evaluation of how successfully this model would “classify” a plant as the correct species, using a 50% cutoff.</p>
<pre class="r"><code>blr1_fitted &lt;- palm_blr1 %&gt;% # fitted column reports the probability that an individual is a Serenoa repens
  broom::augment(type.predict = &quot;response&quot;) %&gt;% # instead of taking the log odds we are taking the odds and converting them into a probability
  mutate(predicted_species = ifelse(.fitted &gt;= 0.5, &quot;Serenoa repens&quot;, &quot;Sabal etonia&quot;)) %&gt;% 
  group_by(species) %&gt;% # separate by species
  summarize(number_correctly_identified = sum(species == predicted_species),
            number_total = n()) %&gt;% # number_total is needed to identify percent correctly identified
  mutate(percent_correctly_identified = number_correctly_identified/number_total * 100) %&gt;% 
  select(species, number_correctly_identified, percent_correctly_identified)

setnames(blr1_fitted, old=c(&quot;species&quot;,&quot;number_correctly_identified&quot;, &quot;percent_correctly_identified&quot;), new=c(&quot;Species&quot;,&quot;Number Correctly Identified&quot;, &quot;Percent Correctly Identified&quot;))
kable(blr1_fitted)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Species</th>
<th align="right">Number Correctly Identified</th>
<th align="right">Percent Correctly Identified</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Sabal etonia</td>
<td align="right">5701</td>
<td align="right">92.62388</td>
</tr>
<tr class="even">
<td align="left">Serenoa repens</td>
<td align="right">5548</td>
<td align="right">90.77225</td>
</tr>
</tbody>
</table>
<p>A binary logistic regression model using plant height, canopy length, canopy width and green leaves as predictor variables is better at predicting palmetto species (<em>Serenoa repens</em> and <em>Sabal etonia</em>) than a model using plant height, canopy width and the number of green leaves. The model correctly identified 5701 (92.62%) of <em>Sabal etonia</em> correctly and 5548 (90.77%) of <em>Serenoa repens</em> correctly.</p>
</div>
</div>
<div id="text-analysis-of-2021-ipcc-summary-for-policymakers-report" class="section level2">
<h2>4. Text Analysis of 2021 IPCC Summary for Policymakers Report</h2>
<div id="overview-3" class="section level3">
<h3>Overview</h3>
<p>This script uses R to conduct a text analysis of the 2021 Intergovernmental Panel on Climate Change (IPCC) Summary for Policymakers report.</p>
<p>First, data is wrangled to get tokens into tidy format and remove stop words, next counts for the most frequently used words in the text are visualized, then a sentiment analysis using the NRC lexicon is performed.</p>
<p><strong>Data citation:</strong> IPCC, 2021: Summary for Policymakers. In: Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change [Masson- Delmotte, V., P. Zhai, A. Pirani, S.L. Connors, C. Péan, S. Berger, N. Caud, Y. Chen, L. Goldfarb, M.I. Gomis, M. Huang, K. Leitzell, E. Lonnoy, J.B.R. Matthews, T.K. Maycock, T. Waterfield, O. Yelekçi, R. Yu, and B. Zhou (eds.)]. Cambridge University Press. In Press. <a href="https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_SPM_final.pdf" class="uri">https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_SPM_final.pdf</a></p>
</div>
<div id="load-necessary-packages" class="section level3">
<h3>Load necessary packages</h3>
<pre class="r"><code>library(tidyverse)
library(tidytext)
library(textdata)
library(pdftools)
library(ggwordcloud)
library(here)</code></pre>
</div>
<div id="load-the-2021-ipcc-report" class="section level3">
<h3>Load the 2021 IPCC Report</h3>
<pre class="r"><code>ipcc_text &lt;- pdf_text(here(&#39;data&#39;, &#39;IPCC_2021pdf.pdf&#39;))</code></pre>
</div>
<div id="get-the-ipcc-report-into-a-dataframe-and-remove-stop-words" class="section level3">
<h3>Get the IPCC report into a dataframe and remove stop words</h3>
<pre class="r"><code>ipcc_lines &lt;- data.frame(ipcc_text) %&gt;% 
  mutate(page = 1:n()) %&gt;%
  mutate(text_full = str_split(ipcc_text, pattern = &#39;\\n&#39;)) %&gt;% 
  unnest(text_full) %&gt;% 
  mutate(text_full = str_trim(text_full)) 


ipcc_words &lt;- ipcc_lines %&gt;% 
  unnest_tokens(word, text_full) %&gt;% 
  select(-ipcc_text)

# Remove stop words
head(stop_words)</code></pre>
<pre><code>## # A tibble: 6 × 2
##   word      lexicon
##   &lt;chr&gt;     &lt;chr&gt;  
## 1 a         SMART  
## 2 a&#39;s       SMART  
## 3 able      SMART  
## 4 about     SMART  
## 5 above     SMART  
## 6 according SMART</code></pre>
<pre class="r"><code>ipcc_words_clean &lt;- ipcc_words %&gt;% 
  anti_join(stop_words, by = &#39;word&#39;)</code></pre>
<pre class="r"><code># Count
nonstop_ipcc_counts &lt;- ipcc_words_clean %&gt;% 
  count(page, word)</code></pre>
</div>
<div id="find-the-top-15-words-from-the-document" class="section level3">
<h3>Find the top 15 words from the document</h3>
<pre class="r"><code>top15 &lt;- nonstop_ipcc_counts %&gt;% 
  arrange(-n) %&gt;% 
  slice(1:15)


cloud &lt;- ggplot(data = top15, 
                     aes(label = word)) +
  geom_text_wordcloud(aes(color = n, size = n), shape = &quot;diamond&quot;) +
  scale_size_area(max_size = 6) +
  scale_color_gradientn(colors = c(&quot;darkgreen&quot;,&quot;blue&quot;,&quot;purple&quot;)) +
  theme_minimal()
 
cloud</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p><strong>Figure 1.</strong> Wordcloud of the 15 most frequently used words in the 2021 IPCC report.</p>
</div>
<div id="sentiment-analysis-with-nrc-lexicon" class="section level3">
<h3>Sentiment analysis with NRC lexicon</h3>
<p>NRC lexicon:<a href="https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm" class="uri">https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm</a></p>
<p>Includes 8 emotions (anger, anticipation, disgust, fear, joy, sadness, surprise, trust).</p>
<pre class="r"><code>ipcc_nrc &lt;- ipcc_words_clean %&gt;% 
  inner_join(get_sentiments(&quot;nrc&quot;))</code></pre>
<pre class="r"><code># Find the count of words by page and sentiment bin: 
ipcc_nrc_counts &lt;- ipcc_nrc %&gt;% 
  count(page, sentiment)

ggplot(data = ipcc_nrc_counts, aes(x = sentiment, y = n)) +
  geom_col() +
  theme_minimal() +
  coord_flip() + 
  ggtitle(&quot;Sentiment Analysis of 2021 IPCC Report\nusing NRC Lexicon&quot;) +
  labs(x = &quot;Sentiment&quot;,
       y = &quot;Count&quot;)</code></pre>
<p><img src="projects_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p><strong>Figure 2.</strong> Graph of the results of a sentiment analysis, using the NRC lexicon, for the 2021 IPCC report.</p>
</div>
</div>

<!--radix_placeholder_site_after_body-->
<!--/radix_placeholder_site_after_body-->
<!--radix_placeholder_navigation_after_body-->
<!--/radix_placeholder_navigation_after_body-->



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
